# Generated by Django 4.0 on 2022-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='origin',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
