# Generated by Django 4.0 on 2022-01-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingaddress_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='origin',
            new_name='region',
        ),
    ]
