# Generated by Django 4.0 on 2022-01-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_origin_shippingaddress_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='price',
        ),
    ]
