# Generated by Django 4.0.4 on 2023-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-id']},
        ),
    ]
