# Generated by Django 4.0 on 2022-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_review_name_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
