# Generated by Django 4.0 on 2022-02-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_number_reviews_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
