# Generated by Django 4.0 on 2022-02-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
